// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfjWy4Ms7P3qysO68-6sBvkCF-gIbr_Iw',
    appId: '1:323837126243:web:5937067f24bc53c652ba56',
    messagingSenderId: '323837126243',
    projectId: 'translink-5a458',
    authDomain: 'translink-5a458.firebaseapp.com',
    storageBucket: 'translink-5a458.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVKGMDoCL3HJ32hIBx_v9nlp-UHLM069c',
    appId: '1:323837126243:android:74df1b04e62e792452ba56',
    messagingSenderId: '323837126243',
    projectId: 'translink-5a458',
    storageBucket: 'translink-5a458.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAccizlCLHgxnX_LMRj2a_qcAm74tD78_w',
    appId: '1:323837126243:ios:57d3c4b56302310252ba56',
    messagingSenderId: '323837126243',
    projectId: 'translink-5a458',
    storageBucket: 'translink-5a458.firebasestorage.app',
    iosBundleId: 'com.example.translink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAccizlCLHgxnX_LMRj2a_qcAm74tD78_w',
    appId: '1:323837126243:ios:57d3c4b56302310252ba56',
    messagingSenderId: '323837126243',
    projectId: 'translink-5a458',
    storageBucket: 'translink-5a458.firebasestorage.app',
    iosBundleId: 'com.example.translink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfjWy4Ms7P3qysO68-6sBvkCF-gIbr_Iw',
    appId: '1:323837126243:web:f2a38c28cdb1498352ba56',
    messagingSenderId: '323837126243',
    projectId: 'translink-5a458',
    authDomain: 'translink-5a458.firebaseapp.com',
    storageBucket: 'translink-5a458.firebasestorage.app',
  );
}
